#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

#find . -type f -name "*.py[co]" -delete
#find . -type d -name "__pycache__" -delete

python manage.py migrate
python manage.py load_services
python manage.py runserver 0.0.0.0:8000
