# Generated by Django 2.0.13 on 2020-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cars', '0001_initial'), ('cars', '0002_auto_20200427_1058'), ('cars', '0003_car_carcolor'), ('cars', '0004_car_car_color'), ('cars', '0005_auto_20200427_1422'), ('cars', '0006_remove_car_advert'), ('cars', '0007_carcharacteristicvalue_transmission_type'), ('cars', '0008_carcharacteristicvalue_body_type'), ('cars', '0009_carcharacteristicvalue_engine_type'), ('cars', '0010_car_mileage')]

    dependencies = [
        ('advert', '0002_auto_20200420_0949'),
        ('users', '0001_initial'),
        ('characteristics', '0003_enginetype'),
        ('characteristics', '0002_carbodytype'),
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cars.CarCharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('car_characteristic_ext', models.PositiveIntegerField(default=0)),
                ('car_modification_ext', models.PositiveIntegerField(default=0)),
                ('car_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_characteristic_values', to='cars.CarCharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('year_begin', models.CharField(blank=True, max_length=15)),
                ('year_end', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.CarMark')),
            ],
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option_values', to='cars.CarEquipment')),
                ('car_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option_values', to='cars.CarOption')),
            ],
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('car_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_series', to='cars.CarGeneration')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_series', to='cars.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carmodification',
            name='car_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_modifications', to='cars.CarSerie'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_marks', to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_generations', to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_equipments', to='cars.CarModification'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='car_options',
            field=models.ManyToManyField(blank=True, through='cars.CarOptionValue', to='cars.CarOption'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_characteristic_values', to='cars.CarModification'),
        ),
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarEquipment')),
                ('car_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarGeneration')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarMark')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarModel')),
                ('car_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarModification')),
                ('car_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarSerie')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarColor'),
        ),
        migrations.RemoveField(
            model_name='car',
            name='profile',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarEquipment'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarGeneration'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarMark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarModel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarModification'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarSerie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.TransmissionType'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.CarBodyType'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.EngineType'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
