# Generated by Django 2.0.13 on 2020-04-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cars.CarCharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('car_characteristic_ext', models.PositiveIntegerField(default=0)),
                ('car_modification_ext', models.PositiveIntegerField(default=0)),
                ('car_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_characteristic_values', to='cars.CarCharacteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('year_begin', models.CharField(blank=True, max_length=15)),
                ('year_end', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.CarMark')),
            ],
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option_values', to='cars.CarEquipment')),
                ('car_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option_values', to='cars.CarOption')),
            ],
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('car_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_series', to='cars.CarGeneration')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_series', to='cars.CarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carmodification',
            name='car_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_modifications', to='cars.CarSerie'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_marks', to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_generations', to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_equipments', to='cars.CarModification'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='car_options',
            field=models.ManyToManyField(blank=True, through='cars.CarOptionValue', to='cars.CarOption'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_characteristic_values', to='cars.CarModification'),
        ),
    ]
