# Generated by Django 2.2.5 on 2020-05-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
