# Generated by Django 2.0.13 on 2020-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
