# Generated by Django 2.0.13 on 2020-04-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cars', '0002_auto_20200427_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarEquipment')),
                ('car_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarGeneration')),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarMark')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarModel')),
                ('car_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarModification')),
                ('car_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarSerie')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.CarType')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
