# Generated by Django 2.0.13 on 2020-04-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_carcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarColor'),
        ),
    ]
