# Generated by Django 2.2.5 on 2020-05-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200525_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
