# Generated by Django 2.0.13 on 2020-04-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20200420_0949'),
        ('cars', '0004_car_car_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='profile',
        ),
        migrations.AddField(
            model_name='car',
            name='advert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='advert.Advert'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarEquipment'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarGeneration'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarMark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarModel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarModification'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarSerie'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.CarType'),
        ),
    ]
