# Generated by Django 2.2.5 on 2020-05-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200523_1221'),
        ('cars', '0004_car_engine_power'),
    ]

    operations = [
    ]
