# Generated by Django 2.0.13 on 2020-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200427_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='advert',
        ),
    ]
