# Generated by Django 2.0.13 on 2020-04-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('cars', '0006_remove_car_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='transmission_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.TransmissionType'),
        ),
    ]
