# Generated by Django 2.2.5 on 2020-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200526_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
