# Generated by Django 2.0.13 on 2020-05-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_fuel_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='max_torque',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
