# Generated by Django 2.0.13 on 2020-04-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_carbodytype'),
        ('cars', '0007_carcharacteristicvalue_transmission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.CarBodyType'),
        ),
    ]
