# Generated by Django 2.2.5 on 2020-07-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20200529_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_ext',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
