# Generated by Django 2.0.13 on 2020-04-29 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_enginetype'),
        ('cars', '0008_carcharacteristicvalue_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.EngineType'),
        ),
    ]
