# Generated by Django 2.0.13 on 2020-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_carcharacteristicvalue_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
