# Generated by Django 2.0.13 on 2020-05-05 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0004_drivetype'),
        ('cars', '0010_car_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='drive_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='characteristics.DriveType'),
        ),
    ]
