# Generated by Django 2.2.5 on 2020-08-06 06:45

from django.db import migrations
import csv


def call_load(apps, schema_editor):
    MultipleOption = apps.get_model("cars", "MultipleOption")

    with open('fixtures/options.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            if row[3] == 'TRUE':
                MultipleOption.objects.create(
                    name=row[0],
                    separator_id=row[4]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20200806_1227'),
    ]

    operations = [
        migrations.RunPython(call_load)
    ]
