# Generated by Django 2.2.5 on 2020-08-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_load_multiple_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cars.Car'),
        ),
    ]
