# Generated by Django 2.2.5 on 2020-08-12 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_car_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cars.Car'),
        ),
    ]
