# Generated by Django 2.2.5 on 2020-08-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_carmark_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='state_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
