# Generated by Django 2.2.5 on 2020-08-20 09:11

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20200820_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolor',
            name='rgb',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
