# Generated by Django 2.2.5 on 2020-08-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_carcolor_rgb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcolor',
            name='rgb',
        ),
        migrations.AddField(
            model_name='carcolor',
            name='b_abbreviation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carcolor',
            name='g_abbreviation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carcolor',
            name='r_abbreviation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
