# Generated by Django 2.2.5 on 2020-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_auto_20200820_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='cruise_control',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Круиз-контроль'), (2, 'Адаптивный круиз-контроль')], null=True, verbose_name='Круиз-контроль'),
        ),
    ]
