# Generated by Django 2.2.5 on 2020-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_auto_20200824_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='airbag',
            field=models.ManyToManyField(blank=True, related_name='airbags', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='electric_heating',
            field=models.ManyToManyField(blank=True, related_name='electric_heating', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='heated_seat',
            field=models.ManyToManyField(blank=True, related_name='heated_seats', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='isofix_fastening_system',
            field=models.ManyToManyField(blank=True, related_name='isofix_fastening_systems', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='parking_assistance_system',
            field=models.ManyToManyField(blank=True, related_name='parking_assistance_systems', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='power_window',
            field=models.ManyToManyField(blank=True, related_name='power_windows', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='seat_electric_adjustment',
            field=models.ManyToManyField(blank=True, related_name='seat_electric_adjustments', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='seat_ventilation',
            field=models.ManyToManyField(blank=True, related_name='seats_ventilation', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='steering_wheel_adjustment',
            field=models.ManyToManyField(blank=True, related_name='steering_wheel_adjustments', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='support_system',
            field=models.ManyToManyField(blank=True, related_name='support_systems', to='cars.MultipleOption'),
        ),
        migrations.AlterField(
            model_name='option',
            name='suspension',
            field=models.ManyToManyField(blank=True, related_name='suspensions', to='cars.MultipleOption'),
        ),
    ]
