version: '3.7'

volumes:
  caps_postgres_data:
    external: true
  caps_postgres_data_backups:
    external: true
  caps_redis:
    external: true

# Here some extensions
x-django_base: &django_base
  build:
    context: .
    dockerfile: ./compose/test/django/Dockerfile
  image: "${CI_REGISTRY}/${CI_REGISTRY_USER}/nomad_auto_advert/test_django:${CI_COMMIT_SHA}"
  depends_on:
    - postgres
    - redis
  env_file:
    - ./.envs/.test/.django
    - ./.envs/.test/.postgres
  command: /start
  networks:
    - masternet
    - db
    - broker

x-django_deploy_base: &django_deploy_base
  placement:
    constraints: [node.hostname == backtest]

x-django_deploy_replicas: &django_deploy_replicas
  replicas: 2

services:
  django:
    <<: *django_base
    deploy:
      <<: *django_deploy_base
      <<: *django_deploy_replicas
      labels:
        - "traefik.enable=true"
        - "traefik.port=5000"
        - "traefik.docker.network=masternet"
        - "traefik.frontend.rule=Host:advert.test.auto-nomad.kz,advert"
        - "traefik.backend=nomad_auto_advert"
        - "traefik.backend.healthcheck.path=/api/microservices/health-check/"
        - "traefik.backend.healthcheck.interval=1s"
        - "traefik.backend.healthcheck.port=5000"
        - "traefik.backend.healthcheck.scheme=http"
        - "traefik.backend.healthcheck.hostname=request.test.auto-nomad.kz"

  postgres:
    build:
      context: .
      dockerfile: ./compose/test/postgres/Dockerfile
    image: "${CI_REGISTRY}/${CI_REGISTRY_USER}/nomad_auto_advert/test_postgres:${CI_COMMIT_SHA}"
    volumes:
      - caps_postgres_data:/var/lib/postgresql/data
      - caps_postgres_data_backups:/backups
    env_file:
      - ./.envs/.test/.postgres
    networks:
      - db
    deploy:
      <<: *django_deploy_base

#  mailhog:
#    image: mailhog/mailhog:v1.0.0
#    networks:
#      - masternet
#    deploy:
#      labels:
#        - "traefik.enable=true"
#        - "traefik.port=8025"
#        - "traefik.docker.network=masternet"
#        - "traefik.frontend.rule=Host:mailhog.nomad_auto_advert.test.auto-nomad.kz"

  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - caps_redis:/data
    networks:
      - broker
    deploy:
      <<: *django_deploy_base

  celeryworker:
    <<: *django_base
    deploy:
      <<: *django_deploy_base
    command: /start-celeryworker

  celerybeat:
    <<: *django_base
    deploy:
      <<: *django_deploy_base
    command: /start-celerybeat

  flower:
    <<: *django_base
    deploy:
      <<: *django_deploy_base
      labels:
        - "traefik.enable=true"
        - "traefik.port=5555"
        - "traefik.docker.network=masternet"
        - "traefik.frontend.rule=Host:flower.nomad_auto_advert.test.auto-nomad.kz"
    command: /start-flower

networks:
  db:
    driver: overlay
    attachable: true
  masternet:
    external: true
  broker:
    driver: overlay
    attachable: true
