# Generated by Django 2.2.5 on 2020-05-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_enginevolumetype'),
        ('filters', '0002_cardrivetype_carenginetype_cartransmissiontype'),
    ]

    operations = [
    ]
