# Generated by Django 2.0.13 on 2020-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ext', models.PositiveIntegerField(unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.IntegerField(choices=[(0, 'Физическое лицо'), (1, 'Юридическое лицо')], default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь',
            },
        ),
    ]
