# Generated by Django 2.2.5 on 2020-08-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactphone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactphone',
            unique_together={('profile', 'phone')},
        ),
    ]
