# Generated by Django 2.2.5 on 2020-08-27 05:03

from django.db import migrations


def delete_contact_phones(apps, schema_editor):
    ContactPhone = apps.get_model("users", "ContactPhone")
    ContactPhone.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactphone'),
    ]

    operations = [
        migrations.RunPython(delete_contact_phones),
        migrations.AlterUniqueTogether(
            name='contactphone',
            unique_together={('profile', 'phone')},
        ),
    ]
