# Generated by Django 2.0.13 on 2020-05-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_enginetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
