# Generated by Django 2.0.13 on 2020-05-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('advert', '0001_initial'), ('advert', '0002_auto_20200420_0949'), ('advert', '0003_advert_car')]

    dependencies = [
        ('cars', '0006_remove_car_advert'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_ext', models.PositiveIntegerField()),
                ('car_condition_type', models.IntegerField(blank=True, choices=[(0, 'Новый'), (1, 'На ходу'), (2, 'Не на ходу'), (3, 'Аварийная')], null=True)),
                ('cleared_by_customs', models.BooleanField(default=False)),
                ('city_ext', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=99)),
                ('exchange', models.BooleanField(default=False)),
                ('to_order', models.BooleanField(default=False)),
                ('rule_type', models.IntegerField(blank=True, choices=[(0, 'Справа'), (1, 'Слева')], default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertContactPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_phones', to='advert.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('advert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert_images', to='advert.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarBodyState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('painted', models.BooleanField(default=False)),
                ('scratched', models.BooleanField(default=False)),
                ('dent', models.BooleanField(default=False)),
                ('rust', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='rule_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Справа'), (1, 'Слева')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='carbodystate',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_body_state', to='advert.Advert'),
        ),
        migrations.AddField(
            model_name='carbodystate',
            name='car_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_body_state', to='advert.CarBody'),
        ),
        migrations.AddField(
            model_name='advert',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='cars.Car'),
        ),
    ]
