# Generated by Django 2.2.5 on 2020-07-23 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='car_condition_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Новый'), (1, 'На ходу'), (2, 'Не на ходу'), (3, 'Аварийная')], null=True, verbose_name='Состояние машины'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='city_ext',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='cleared_by_customs',
            field=models.BooleanField(default=False, verbose_name='Растаможен'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактная почта'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное имя'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='exchange',
            field=models.BooleanField(default=False, verbose_name='Возможен обмен'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=99, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='rule_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Справа'), (1, 'Слева')], default=1, null=True, verbose_name='Тип руля'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='to_order',
            field=models.BooleanField(default=False, verbose_name='На заказ'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='users.Profile'),
        ),
    ]
