# Generated by Django 2.0.13 on 2020-04-20 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarBodyState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('painted', models.BooleanField(default=False)),
                ('scratched', models.BooleanField(default=False)),
                ('dent', models.BooleanField(default=False)),
                ('rust', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='rule_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Справа'), (1, 'Слева')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='carbodystate',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_body_state', to='advert.Advert'),
        ),
        migrations.AddField(
            model_name='carbodystate',
            name='car_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_body_state', to='advert.CarBody'),
        ),
    ]
