# Generated by Django 2.0.13 on 2020-04-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_advert'),
        ('advert', '0002_auto_20200420_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='cars.Car'),
        ),
    ]
