# Generated by Django 2.2.5 on 2020-07-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('advert', '0002_auto_20200723_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='city_ext',
        ),
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='geo.City'),
        ),
    ]
