# Generated by Django 2.2.5 on 2020-07-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20200727_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertimage',
            name='advert',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='advert_images', to='advert.Advert'),
            preserve_default=False,
        ),
    ]
