# Generated by Django 2.2.5 on 2020-07-29 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20200727_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='car',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='cars.Car'),
            preserve_default=False,
        ),
    ]
