# Generated by Django 2.2.5 on 2020-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20200729_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
