# Generated by Django 2.2.5 on 2020-08-03 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200723_1129'),
        ('advert', '0006_advert_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='advert.Advert')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
