# Generated by Django 2.2.5 on 2020-08-03 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200723_1129'),
        ('advert', '0007_advertfavourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_spam', models.BooleanField(default=False)),
                ('is_inappropriate_content', models.BooleanField(default=False)),
                ('is_fake_information', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='advert.Advert')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='users.Profile')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
