# Generated by Django 2.2.5 on 2020-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_advertcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='car_ext',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
