# Generated by Django 2.2.5 on 2020-08-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_auto_20200813_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertContactPhone',
        ),
    ]
