# Generated by Django 2.2.5 on 2020-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contactphone'),
        ('advert', '0010_delete_advertcontactphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='contact_phones',
            field=models.ManyToManyField(related_name='contact_phones', to='users.ContactPhone'),
        ),
    ]
