# Generated by Django 2.2.5 on 2020-08-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0012_advertcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='advert.AdvertComment'),
        ),
    ]
