# Generated by Django 2.2.5 on 2020-08-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0014_auto_20200828_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='id_archived',
            new_name='is_archived',
        ),
        migrations.RenameField(
            model_name='advert',
            old_name='id_hidden',
            new_name='is_hidden',
        ),
    ]
