# Generated by Django 2.2.5 on 2020-09-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0015_auto_20200828_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='is_archived',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'moderation'), (3, 'active'), (4, 'archived')], default=1),
        ),
    ]
