# Generated by Django 2.2.5 on 2020-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0016_auto_20200901_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='in_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'created'), (2, 'active'), (3, 'archived')], default=1),
        ),
    ]
