# Generated by Django 2.2.5 on 2020-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)'),
        ),
    ]
